/**
 * Task priority levels
 */
export enum TaskPriority {
  Low = 0,
  General = 1,
  Medium = 2,
  High = 3,
}

/**
 * Avatar mode
 */
export enum AvatarMode {
  Uploaded = 0,
  Upload = 1,
  Generated = 2,
}

// Legacy aliases for backward compatibility
/** @deprecated Use AvatarMode.Uploaded instead */
export const AvatarModeInitials = AvatarMode.Uploaded;
/** @deprecated Use AvatarMode.Generated instead */
export const AvatarModeAvatar = AvatarMode.Generated;

/**
 * Entity kind/type
 */
export enum Kind {
  Task = 'Task',
  Document = 'Document',
  Milestone = 'Milestone',
  User = 'User',
  Project = 'Project',
  Space = 'Space',
  Member = 'Member',
}

/**
 * Custom field types
 */
export enum CustomFieldType {
  TEXT = 'Text',
  NUMBER = 'Number',
  CHECKBOX = 'Checkbox',
  DATE = 'Date',
  MEMBER = 'Member',
  TASK_RELATIONS = 'TaskRelations',
  SELECT = 'Select',
  URL = 'Url',
}

/**
 * Color options for select fields
 */
export enum Color {
  Silver = 'silver',
  Red = 'red',
  Orange = 'orange',
  Gold = 'gold',
  Olive = 'olive',
  Green = 'green',
  Mint = 'mint',
  Blue = 'blue',
  Violet = 'violet',
  Lavender = 'lavender',
  Magenta = 'magenta',
  Rose = 'rose',
  // Legacy aliases for backward compatibility
  Yellow = 'Yellow',
  Teal = 'Teal',
  Purple = 'Purple',
  Gray = 'Gray',
}

/**
 * Icon options for select fields
 */
export enum Icon {
  Cursor = 'Cursor',
  Square = 'Square',
  Hexagon = 'Hexagon',
  Rhombus = 'Rhombus',
  Triangle = 'Triangle',
  Checkbox = 'Checkbox',
  Diamonds = 'Diamonds',
  Circle = 'Circle',
  Light = 'Light',
  Search = 'Search',
  Stop = 'Stop',
  User = 'User',
  People = 'People',
  UserGroup2 = 'UserGroup2',
  ConnectedPeople = 'ConnectedPeople',
  Col = 'Col',
  Code = 'Code',
  Todo = 'Todo',
  Board = 'Board',
  Document = 'Document',
  Project = 'Project',
  Air = 'Air',
  Atom = 'Atom',
  Molecule = 'Molecule',
  Battery = 'Battery',
  BatteryCharging = 'BatteryCharging',
  BatteryLevel = 'BatteryLevel',
  BenzeneRing = 'BenzeneRing',
  BGRemover = 'BGRemover',
  Barcode = 'Barcode',
  QR = 'QR',
  Basilica = 'Basilica',
  Basketball = 'Basketball',
  Binoculars = 'Binoculars',
  BlackHat = 'BlackHat',
  Hat = 'Hat',
  Bot = 'Bot',
  Broom = 'Broom',
  CampingChair = 'CampingChair',
  Cable = 'Cable',
  Terminal = 'Terminal',
  Rs232Female = 'Rs232Female',
  CD = 'CD',
  Music = 'Music',
  Music2 = 'Music2',
  MusicPlaylist = 'MusicPlaylist',
  Swap = 'Swap',
  Camera = 'Camera',
  Camera2 = 'Camera2',
  Aperture = 'Aperture',
  Clock = 'Clock',
  Watch = 'Watch',
  Tenses = 'Tenses',
  Voicemail = 'Voicemail',
  WatchesFrontView = 'WatchesFrontView',
  WeddingRings = 'WeddingRings',
  List = 'List',
  Restart = 'Restart',
  Target = 'Target',
  Moon = 'Moon',
  Sun = 'Sun',
  Cloud = 'Cloud',
  Snow = 'Snow',
  Fire = 'Fire',
  Drop = 'Drop',
  DoctorsBag = 'DoctorsBag',
  Hospital = 'Hospital',
  MedicalDoctor = 'MedicalDoctor',
  ELearning = 'ELearning',
  Laptop = 'Laptop',
  FanSpeed = 'FanSpeed',
  MindMap = 'MindMap',
  Mirror = 'Mirror',
  Attach = 'Attach',
  Flag = 'Flag',
  Finish = 'Finish',
  Crown = 'Crown',
  Money = 'Money',
  Coins = 'Coins',
  Shield = 'Shield',
  Trophy = 'Trophy',
  WomanHead = 'WomanHead',
  Knight = 'Knight',
  Bug = 'Bug',
  Bird = 'Bird',
  PeacePigeon = 'PeacePigeon',
  Penguin = 'Penguin',
  Fish = 'Fish',
  Alien = 'Alien',
  Panda = 'Panda',
  Cat = 'Cat',
  Dog = 'Dog',
  Unicorn = 'Unicorn',
  Run = 'Run',
  Swimming = 'Swimming',
  Ball = 'Ball',
  Geography = 'Geography',
  Planet = 'Planet',
  Location = 'Location',
  Navigate = 'Navigate',
  Stormtrooper = 'Stormtrooper',
  SpaceFighter = 'SpaceFighter',
  Submarine = 'Submarine',
  GpsSignal = 'GpsSignal',
  Radio = 'Radio',
  InternetAntenna = 'InternetAntenna',
  Satellites = 'Satellites',
  Satellite = 'Satellite',
  Speed = 'Speed',
  Plane = 'Plane',
  Ship = 'Ship',
  ShipWheel = 'ShipWheel',
  Lifebuoy = 'Lifebuoy',
  Launch = 'Launch',
  Car = 'Car',
  BikePath = 'BikePath',
  Cycling = 'Cycling',
  MotorbikeHelmet = 'MotorbikeHelmet',
  Road = 'Road',
  Video = 'Video',
  Play = 'Play',
  New = 'New',
  Table = 'Table',
  Chart = 'Chart',
  Rename = 'Rename',
  Broadcast = 'Broadcast',
  Sound = 'Sound',
  Info = 'Info',
  Help = 'Help',
  Quote = 'Quote',
  Attention = 'Attention',
  Add = 'Add',
  Percent = 'Percent',
  Percent0 = 'Circle',
  Percent25 = '25%',
  Percent50 = '50%',
  Percent75 = '75%',
  Percent100 = '100%',
  Thumb = 'Thumb',
  Delete = 'Delete',
  Type = 'Type',
  Asterisk = 'Asterisk',
  Email = 'Email',
  Mail = 'Mail',
  Message = 'Message',
  Image = 'Image',
  Coffee = 'Coffee',
  Heart = 'Heart',
  Star = 'Star',
  Link = 'Link',
  Happy = 'Happy',
  Phone = 'Phone',
  Layers = 'Layers',
  Chat = 'Chat',
  Apps = 'Apps',
  Up = 'Up',
  Lab = 'Lab',
  Cancel = 'Cancel',
  Poo = 'Poo',
  Skull = 'Skull',
  Bone = 'Bone',
  Dice = 'Dice',
  Puzzle = 'Puzzle',
  Bang = 'Bang',
  Explosion = 'Explosion',
  Gun = 'Gun',
  Shower = 'Shower',
  SpaFlower = 'SpaFlower',
  FoamBubbles = 'FoamBubbles',
  Galaxy = 'Galaxy',
  Beer = 'Beer',
  Champagne = 'Champagne',
  WineGlass = 'WineGlass',
  Cocktail = 'Cocktail',
  Plate = 'Plate',
  Bookmark = 'Bookmark',
  Book = 'Book',
  Sent = 'Sent',
  Home = 'Home',
  MarkerPen = 'MarkerPen',
  Illustrator = 'Illustrator',
  Paint = 'Paint',
  Paint2 = 'Paint2',
  Gear = 'Gear',
  BoxClose = 'BoxClose',
  Alpha = 'Alpha',
  Beta = 'Beta',
  Gamma = 'Gamma',
  Lambda = 'Lambda',
  Mu = 'Mu',
  Omega = 'Omega',
  Pi = 'Pi',
  Sigma = 'Sigma',
  TypeText = 'TypeText',
  TypeNumber = 'TypeNumber',
  TypeDate = 'TypeDate',
  TypeCheck = 'TypeCheck',
  TypeUser = 'TypeUser',
  // Legacy aliases for backward compatibility
  Check = 'Check',
  Alert = 'Alert',
}

/**
 * Upload file types
 */
export enum UploadFileType {
  Image = 'Image',
  Video = 'Video',
  Pdf = 'Pdf',
  File = 'File',
}

/**
 * Comment reaction types
 */
export enum CommentReactionType {
  THUMBS_UP = 'thumbs_up',
  HEART = 'heart',
  LAUGHING = 'joy',
  WOW = 'open_mouth',
  CRYING = 'cry',
  ANGRY = 'angry',
  PARTY = 'tada',
  // Legacy aliases for backward compatibility
  Like = 'like',
  Love = 'love',
  Laugh = 'laugh',
  Surprised = 'surprised',
  Sad = 'sad',
}

/**
 * Embed types for embed blocks
 */
export enum EmbedType {
  YouTube = 'YouTube',
  Figma = 'Figma',
  Vimeo = 'Vimeo',
  CodeSandbox = 'CodeSandbox',
  GitHubGist = 'GitHub Gist',
  Miro = 'Miro',
  Iframe = 'Iframe',
}

/**
 * Comment reaction metadata based on emoji-picker-react standards
 */
export const COMMENT_REACTION_METADATA = {
  [CommentReactionType.THUMBS_UP]: {
    id: '1f44d',
    name: 'Thumbs Up Sign',
    native: '👍',
    unified: '1f44d',
    keywords: ['thumbsup', 'yes', 'awesome', 'good', 'agree', 'accept', 'cool', 'hand', 'like'],
    shortcodes: ':thumbsup:',
    emoji: '👍',
    label: 'Like',
  },
  [CommentReactionType.HEART]: {
    id: '2764-fe0f',
    name: 'Red Heart',
    native: '❤️',
    unified: '2764-fe0f',
    keywords: ['love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'heart'],
    shortcodes: ':heart:',
    emoji: '❤️',
    label: 'Love',
  },
  [CommentReactionType.LAUGHING]: {
    id: '1f602',
    name: 'Face with Tears of Joy',
    native: '😂',
    unified: '1f602',
    keywords: ['face', 'tears', 'joy', 'laugh', 'happy', 'funny', 'haha', 'lol'],
    shortcodes: ':joy:',
    emoji: '😂',
    label: 'Laugh',
  },
  [CommentReactionType.WOW]: {
    id: '1f62e',
    name: 'Face with Open Mouth',
    native: '😮',
    unified: '1f62e',
    keywords: ['face', 'surprise', 'impressed', 'wow', 'whoa', 'amazed', 'gasp'],
    shortcodes: ':open_mouth:',
    emoji: '😮',
    label: 'Surprised',
  },
  [CommentReactionType.CRYING]: {
    id: '1f622',
    name: 'Crying Face',
    native: '😢',
    unified: '1f622',
    keywords: ['face', 'tears', 'sad', 'depressed', 'upset', 'cry'],
    shortcodes: ':cry:',
    emoji: '😢',
    label: 'Sad',
  },
  [CommentReactionType.ANGRY]: {
    id: '1f621',
    name: 'Pouting Face',
    native: '😡',
    unified: '1f621',
    keywords: ['mad', 'face', 'annoyed', 'frustrated', 'pouting', 'angry'],
    shortcodes: ':rage:',
    emoji: '😡',
    label: 'Angry',
  },
  [CommentReactionType.PARTY]: {
    id: '1f389',
    name: 'Party Popper',
    native: '🎉',
    unified: '1f389',
    keywords: ['party', 'congratulations', 'birthday', 'celebration', 'tada'],
    shortcodes: ':tada:',
    emoji: '🎉',
    label: 'Party',
  },
  // Legacy aliases for backward compatibility
  [CommentReactionType.Like]: {
    id: '1f44d',
    name: 'Thumbs Up Sign',
    native: '👍',
    unified: '1f44d',
    keywords: ['thumbsup', 'yes', 'awesome', 'good', 'agree', 'accept', 'cool', 'hand', 'like'],
    shortcodes: ':thumbsup:',
    emoji: '👍',
    label: 'Like',
  },
  [CommentReactionType.Love]: {
    id: '2764-fe0f',
    name: 'Red Heart',
    native: '❤️',
    unified: '2764-fe0f',
    keywords: ['love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'heart'],
    shortcodes: ':heart:',
    emoji: '❤️',
    label: 'Love',
  },
  [CommentReactionType.Laugh]: {
    id: '1f602',
    name: 'Face with Tears of Joy',
    native: '😂',
    unified: '1f602',
    keywords: ['face', 'tears', 'joy', 'laugh', 'happy', 'funny', 'haha', 'lol'],
    shortcodes: ':joy:',
    emoji: '😂',
    label: 'Laugh',
  },
  [CommentReactionType.Surprised]: {
    id: '1f62e',
    name: 'Face with Open Mouth',
    native: '😮',
    unified: '1f62e',
    keywords: ['face', 'surprise', 'impressed', 'wow', 'whoa', 'amazed', 'gasp'],
    shortcodes: ':open_mouth:',
    emoji: '😮',
    label: 'Surprised',
  },
  [CommentReactionType.Sad]: {
    id: '1f622',
    name: 'Crying Face',
    native: '😢',
    unified: '1f622',
    keywords: ['face', 'tears', 'sad', 'depressed', 'upset', 'cry'],
    shortcodes: ':cry:',
    emoji: '😢',
    label: 'Sad',
  },
};
